name: Deploy to AWS EC2

on:
    push:
        branches:
            - main

jobs:
    pull-and-switch:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to EC2 via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd carportal_frontend
                      sudo git pull
                      sudo npm install
                      sudo env VITE_API_URL=https://saarcodes.dev npm run build
                      sudo rm -rf /var/www/saarcodes.dev/*
                      sudo cp -r dist/* /var/www/saarcodes.dev/
                      sudo chown -R www-data:www-data /var/www/saarcodes.dev
                      sudo chmod -R 755 /var/www/saarcodes.dev
                      sudo systemctl reload nginx
