name: Deploy to AWS EC2

on:
    push:
        branches:
            - main

jobs:
    pull-and-switch:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to EC2 via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                    cd carportal_frontend
                    sudo git pull
                    sudo npm install
                    sudo npm run build
                    sudo rm -rf /var/www/domain/*
                    sudo cp -r dist/* /var/www/domain/
                    sudo chown -R www-data:www-data /var/www/domain
                    sudo chmod -R 755 /var/www/domain
                    sudo systemctl reload nginx
